apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gtws.gtw.fabric8.org
spec:
  group: gtw.fabric8.org
  names:
    kind: GTW
    listKind: GTWList
    plural: gtws
    singular: gtw
  scope: Namespaced
  version: v1alpha1
