apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtw-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gtw-operator
  template:
    metadata:
      labels:
        name: gtw-operator
    spec:
      containers:
        - name: gtw-operator
          image: 172.30.1.1:5000/gtw/operator:v0.0.2
          command:
          - gtw-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
